feign:
  client:
    config:
#      jplaceholder:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
#        requestInterceptors: com.baeldung.cloud.openfeign.JSONPlaceHolderInterceptor
#      jplaceholder:
